docker:
  db: {}
domains: []
global:
  name: config
  type: app
  version: 6.6.2
test:
  coverage:
    last_report:
      covered: 448
      excluded: 32
      missing: 390
      percent: 53.46062052505967
      total: 838
wex:
  migration: 1
  version: 6.0.112
